### MBA 商數作業

In [1]:
# Logistic Regression
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Importing training dataset
df_train = pd.read_excel('Train.xlsx', sheetname='Survey Data')
df_train = df_train.set_index('ID')
df_train.head()

CarType  Gender  Age  Income  CreditScore  Payment  Accident  Complaint  \
ID                                                                            
1         2       0   65  130.67           92        0         0          0   
2         4       1   40   93.93           68        0         0          0   
3         3       1   44   90.03           89        0         0          0   
4         1       0   61  126.96           85        0         0          2   
5         3       1   29  105.02           72        2         0          1   

    OwnHouse  Repeat  City  Mileage  Buy1  Buy2  
ID                                               
1          1       0     0       40     1     0  
2          0       0     1       31     0     0  
3          0       0     1       26     0     0  
4          0       0     0       32     0     0  
5          1       0     1       40     0     1

In [6]:
# Importing testing dataset
df_test = pd.read_excel('Test.xlsx', sheetname='Sheet1')
df_test = df_test.set_index('ID')
df_test.head()

Gender  Age  Income  CreditScore  Payment  Accident  Complaint  OwnHouse  \
ID                                                                             
1        1   25   83.82           56        0         0          3         0   
2        1   58  108.60           84        0         0          0         0   
3        0   27   88.55           80        0         0          0         1   
4        0   40   88.45           66        1         0          0         0   
5        0   62  112.51           84        0         0          0         1   

    Repeat  City  Mileage  CarType  
ID                                  
1        0     1       28        3  
2        0     1       25        1  
3        0     1       32        4  
4        0     0       24        4  
5        0     1       39        1

In [7]:
# No Scaling-Buy1
X_train_1 = df_train.iloc[:, 1:11].values
y_train_1 = df_train.iloc[:, 12].values
X_test_1 = df_test.iloc[:, :10].values

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_1 = LogisticRegression()
classifier_1.fit(X_train_1, y_train_1)

# Predict
y_pred_1 = classifier_1.predict(X_test_1)
y_pred_1_prob = classifier_1.predict_proba(X_test_1)

In [9]:
y_pred_1_prob[:, 1]

array([ 0.09802796,  0.41211411,  0.45181201,  0.14586373,  0.43679911,
        0.26696204,  0.46223028,  0.42628941,  0.31528385,  0.13837386,
        0.41960371,  0.00208697,  0.27303712,  0.10313476,  0.32270661,
        0.41995686,  0.24493445,  0.40633744,  0.46000022,  0.45074246,
        0.49867808,  0.13230538,  0.00400272,  0.30043369,  0.30190869,
        0.18109543,  0.39242481,  0.08118376,  0.22374965,  0.25509025,
        0.32788105,  0.38831169,  0.21051318,  0.18635025,  0.21095727,
        0.25021876,  0.34315458,  0.28962178,  0.25990121,  0.33312757,
        0.28039322,  0.46439102,  0.42523354,  0.40385574,  0.13692517,
        0.31588025,  0.37691338,  0.54088252,  0.19837373,  0.32996147,
        0.23971651,  0.32143448,  0.36743524,  0.45933567,  0.44329156,
        0.38628681,  0.34517738,  0.11101507,  0.27051683,  0.48014848,
        0.13847218,  0.02791941,  0.5129763 ,  0.24294763,  0.3566597 ,
        0.12275313,  0.23569072,  0.00849216,  0.20884013,  0.12

In [12]:
# No Scaling-Buy2
X_train_2 = df_train.iloc[:, 1:11].values
y_train_2 = df_train.iloc[:, 13].values
X_test_2 = df_test.iloc[:, :10].values

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_2 = LogisticRegression()
classifier_2.fit(X_train_2, y_train_2)

# Predict
y_pred_2 = classifier_2.predict(X_test_2)
y_pred_2_prob = classifier_2.predict_proba(X_test_2)

In [13]:
y_pred_2_prob[:, 1]

array([ 0.09522479,  0.5165724 ,  0.52044273,  0.39478236,  0.56669796,
        0.34436283,  0.38073966,  0.39783812,  0.39087141,  0.15859126,
        0.50685611,  0.00155172,  0.27387668,  0.11640215,  0.34773573,
        0.45280892,  0.24544523,  0.48316992,  0.39345139,  0.40264517,
        0.49246844,  0.16387899,  0.0069181 ,  0.36778279,  0.42002016,
        0.20077823,  0.32102328,  0.09123941,  0.27573568,  0.31786137,
        0.31383869,  0.44516598,  0.22766302,  0.16006618,  0.17693082,
        0.27048653,  0.41824806,  0.31009871,  0.38327031,  0.29585498,
        0.22414729,  0.53384466,  0.34217985,  0.30898014,  0.17719719,
        0.27591175,  0.46784861,  0.53126139,  0.19692407,  0.41904627,
        0.28568208,  0.405133  ,  0.40306167,  0.5187267 ,  0.54949059,
        0.54687979,  0.26353017,  0.09982357,  0.25889527,  0.61178576,
        0.17640868,  0.26376517,  0.58250673,  0.21900989,  0.40183449,
        0.15232797,  0.26852327,  0.01189364,  0.22455821,  0.10

In [14]:
# Scaling-Buy1
X_train_1 = df_train.iloc[:, 1:11].values
y_train_1 = df_train.iloc[:, 12].values
X_test_1 = df_test.iloc[:, :10].values

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_1_1 = sc.fit_transform(X_train_1)
X_test_1_1 = sc.fit_transform(X_test_1)

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_1_1 = LogisticRegression()
classifier_1_1.fit(X_train_1_1, y_train_1)

# Predict
y_pred_1_1 = classifier_1_1.predict(X_test_1_1)
y_pred_1_1_prob = classifier_1_1.predict_proba(X_test_1_1)

In [16]:
y_pred_1_1_prob[:, 1]

array([  6.21108908e-02,   4.26806903e-01,   4.04293601e-01,
         7.53044302e-02,   4.53629204e-01,   1.88774131e-01,
         5.85604196e-01,   5.13475088e-01,   2.30544270e-01,
         1.15220163e-01,   3.56365070e-01,   5.39892276e-04,
         2.20795637e-01,   6.00556722e-02,   2.38658478e-01,
         4.66600072e-01,   2.00008478e-01,   4.60696015e-01,
         6.26014791e-01,   4.97783957e-01,   6.16213000e-01,
         8.42942610e-02,   3.05342815e-04,   3.49695526e-01,
         2.03508179e-01,   9.02128059e-02,   3.70975760e-01,
         4.48998062e-02,   3.38953400e-01,   1.39118185e-01,
         4.03727237e-01,   4.65448358e-01,   1.19492651e-01,
         2.01298985e-01,   1.78249452e-01,   1.37275538e-01,
         3.40194569e-01,   3.40211722e-01,   2.21795742e-01,
         3.95319268e-01,   3.02818754e-01,   5.07200164e-01,
         4.78003292e-01,   4.36087485e-01,   5.49787343e-02,
         2.24344095e-01,   4.70576505e-01,   6.30175554e-01,
         2.17652323e-01,

In [17]:
np.where(y_pred_1_1 == 1)

(array([ 6,  7, 18, 20, 41, 47, 52, 62, 70, 75, 78, 79, 98], dtype=int64),)

In [21]:
# Scaling-Buy2
X_train_2 = df_train.iloc[:, 1:11].values
y_train_2 = df_train.iloc[:, 13].values
X_test_2 = df_test.iloc[:, :10].values

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_2_1 = sc.fit_transform(X_train_2)
X_test_2_1 = sc.fit_transform(X_test_2) 

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_2_1 = LogisticRegression()
classifier_2_1.fit(X_train_2_1, y_train_2)

# Predict
y_pred_2_1 = classifier_2_1.predict(X_test_2_1)
y_pred_2_1_prob = classifier_2_1.predict_proba(X_test_2_1)

In [22]:
y_pred_2_1_prob[:, 1]

array([  7.56003232e-02,   5.29509742e-01,   4.95023437e-01,
         3.32674007e-01,   5.81552647e-01,   2.85621016e-01,
         4.64290270e-01,   4.54977722e-01,   3.31155133e-01,
         1.49440896e-01,   4.66967967e-01,   3.12335191e-04,
         2.40910393e-01,   8.68192193e-02,   2.96012432e-01,
         4.87792786e-01,   2.22854768e-01,   5.29847950e-01,
         5.04611796e-01,   4.32048094e-01,   5.71407067e-01,
         1.28917407e-01,   6.13034367e-04,   4.12338210e-01,
         3.49107582e-01,   1.02424808e-01,   3.11007570e-01,
         4.99692687e-02,   3.70767268e-01,   2.24725518e-01,
         3.70386332e-01,   5.09632641e-01,   1.26934978e-01,
         1.77689670e-01,   1.61031177e-01,   1.92036960e-01,
         4.21281426e-01,   3.52675269e-01,   3.60117955e-01,
         3.37437104e-01,   2.41013801e-01,   5.67686055e-01,
         3.77436322e-01,   3.32907671e-01,   8.03409615e-02,
         2.20565973e-01,   5.40119032e-01,   5.89965551e-01,
         2.14243293e-01,

In [23]:
np.where(y_pred_2_1 == 1)

(array([ 1,  4, 17, 18, 20, 31, 41, 46, 47, 52, 53, 55, 59, 62, 70, 75, 78,
        79, 88, 89, 98], dtype=int64),)

In [28]:
# Report Dataframe
data = {'Buy_1':y_pred_1_1_prob[:, 1],
        'Buy_2':y_pred_2_1_prob[:, 1]}
df = pd.DataFrame(data)
df['ID'] = pd.read_excel('Train.xlsx', sheetname='Survey Data')['ID']
df['Score'] = 0.5* df.Buy_1 + 0.5* df.Buy_2 # 假設兩個PROGRAM權重一樣
df = df.set_index('ID')
df.head()

Buy_1     Buy_2     Score
ID                              
1   0.062111  0.075600  0.068856
2   0.426807  0.529510  0.478158
3   0.404294  0.495023  0.449659
4   0.075304  0.332674  0.203989
5   0.453629  0.581553  0.517591

In [32]:
# Report Score sorting
Report = df.sort_values('Score',ascending=False)
Report.head()

Buy_1     Buy_2     Score
ID                              
76  0.576500  0.682804  0.629652
48  0.630176  0.589966  0.610071
21  0.616213  0.571407  0.593810
99  0.545793  0.630822  0.588307
79  0.514162  0.651438  0.582800

In [33]:
# Report Export
Report = Report[:55]
Report.to_excel("Report.xlsx",sheet_name='Answer')